### ISSUE TITLE
Unpunctuated title in description field

### ISSUE THREAD

**Issue by sfsheath** [isawnyu/isaw.awol#54]
Quoting from my own email: "description field starts out with the title repeated but no punctuation separating it from the text of the description. Or at least it does here: http://pipsqueak.atlantides.org/awol-index/html/daedalus.umkc.edu/415cea8794c5558680ee9d0b055aba2f55def1a5.html and the few other places I clicked. "

**Comment by paregorios** [comment]
I'd hoped that the description line deduplication function would have dealt with this, which is an artifact of parsing content in document order out of arbitrary HTML hierarchies. But apparently there's a common edge case in which it's failing. Will have to hunt it down and see if there's a generalizable fix.
